{'id': '~account.report.line~58|groupby:currency_id~res.currency~1', 'unfoldable': False, 'unfolded': True,
 'groupby': 'account_id,id', 'columns': [
    {'name': '-988.18\xa0€', 'style': 'white-space:nowrap; text-align:right;', 'no_format': '-988.18\xa0€',
     'column_group_key': "(('forced_options', (('date', (('date_from', '2023-11-01'), ('date_to', '2023-11-30'), ('filter', 'last_month'), ('mode', 'single'), ('period_type', 'month'), ('string', 'As of 11/30/2023'))),)), ('horizontal_groupby_element', ()))",
     'auditable': False, 'expression_label': 'balance_currency', 'has_sublines': False, 'report_line_id': 58,
     'class': '', 'is_zero': False},
    {'name': '-32,142.43\xa0LE', 'style': 'white-space:nowrap; text-align:right;', 'no_format': -32142.43,
     'column_group_key': "(('forced_options', (('date', (('date_from', '2023-11-01'), ('date_to', '2023-11-30'), ('filter', 'last_month'), ('mode', 'single'), ('period_type', 'month'), ('string', 'As of 11/30/2023'))),)), ('horizontal_groupby_element', ()))",
     'auditable': False, 'expression_label': 'balance_operation', 'has_sublines': False, 'report_line_id': 58,
     'class': 'number', 'is_zero': False},
    {'name': '-32,142.43\xa0LE', 'style': 'white-space:nowrap; text-align:right;', 'no_format': -32142.432041999997,
     'column_group_key': "(('forced_options', (('date', (('date_from', '2023-11-01'), ('date_to', '2023-11-30'), ('filter', 'last_month'), ('mode', 'single'), ('period_type', 'month'), ('string', 'As of 11/30/2023'))),)), ('horizontal_groupby_element', ()))",
     'auditable': False, 'expression_label': 'balance_current', 'has_sublines': False, 'report_line_id': 58,
     'class': 'number', 'is_zero': False},
    {'name': '', 'style': 'white-space:nowrap; text-align:right;', 'no_format': -0.002041999997634372,
     'column_group_key': "(('forced_options', (('date', (('date_from', '2023-11-01'), ('date_to', '2023-11-30'), ('filter', 'last_month'), ('mode', 'single'), ('period_type', 'month'), ('string', 'As of 11/30/2023'))),)), ('horizontal_groupby_element', ()))",
     'auditable': False, 'expression_label': 'adjustment', 'has_sublines': False, 'report_line_id': 58,
     'class': 'number', 'is_zero': True}], 'level': 2, 'parent_id': '~account.report.line~58',
 'expand_function': '_report_expand_unfoldable_line_with_groupby', 'caret_options': None,
 'name': 'EUR (1 EGP = 0.0307438 EUR)'}
